// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    AppButton: typeof import('./src/shared/components/buttons/app-button.vue')['default']
  }
}

export { }
